language: c
matrix:
  fast_finish: true
  include:
    # OS X Mavericks
    - os: osx
      env: C_COMPILER=clang TOOLSET=clang LTO=on ARCH=native

    # Container-based Ubuntu 12.04 LTS Server Edition 64 bit (doesn't support 32-bit includes)
    - os: linux
      sudo: false
      env: C_COMPILER=gcc TOOLSET=gcc LTO=on ARCH=native

    - os: linux
      sudo: false
      env: C_COMPILER=clang TOOLSET=clang LTO=off ARCH=native

    # Ubuntu 14.04 LTS Server Edition 64 bit
    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-arm
            - qemu-user-static
            - gcc-aarch64-linux-gnu
            - g++-aarch64-linux-gnu
      env: QEMU_INTERPRETER=qemu-aarch64-static GCCPREFIX=aarch64-linux-gnu- TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-arm
            - qemu-user-static
            - gcc-arm-linux-gnueabi
            - g++-arm-linux-gnueabi
      env: QEMU_INTERPRETER=qemu-arm-static GCCPREFIX=arm-linux-gnueabi- TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-ppc
            - qemu-user-static
            - gcc-powerpc-linux-gnu
            - g++-powerpc-linux-gnu
      env: QEMU_INTERPRETER=qemu-ppc64-static GCCPREFIX=powerpc-linux-gnu- TOOLSET=gcc LTO=on ARCH=x64

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-ppc
            - qemu-user-static
            - gcc-powerpc-linux-gnu
            - g++-powerpc-linux-gnu
      env: QEMU_INTERPRETER=qemu-ppc-static GCCPREFIX=powerpc-linux-gnu- TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      env: C_COMPILER=gcc TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - libc6-dev-i386
            - g++-multilib
      env: C_COMPILER=gcc TOOLSET=gcc LTO=on ARCH=x32

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: C_COMPILER=gcc-4.9 TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: C_COMPILER=gcc-5 TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - g++-5-multilib
            - gcc-multilib
      env: C_COMPILER=gcc-5 TOOLSET=gcc LTO=on ARCH=x32

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: C_COMPILER=gcc-6 TOOLSET=gcc LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - g++-6-multilib
            - gcc-multilib
      env: C_COMPILER=gcc-6 TOOLSET=gcc LTO=on ARCH=x32

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.5
          packages:
            - clang-3.5
      env: C_COMPILER=clang-3.5 TOOLSET=clang LTO=on ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.6
          packages:
            - clang-3.6
      env: C_COMPILER=clang-3.6 TOOLSET=clang LTO=off ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
      env: C_COMPILER=clang-3.8 TOOLSET=clang LTO=off ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env: C_COMPILER=clang-3.9 TOOLSET=clang LTO=off ARCH=native

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env: C_COMPILER=clang-4.0 TOOLSET=clang LTO=off ARCH=native

before_install:
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-macosx.tar.gz -O premake.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-linux.tar.gz -O premake.tar.gz; fi

script:
  - tar zxvf premake.tar.gz
  - ./premake5 gmake --toolset=$TOOLSET --lto=$LTO --arch=$ARCH --gccprefix=$GCCPREFIX
  - $C_COMPILER -v
  - make CC=$C_COMPILER
  - ls -la ./bin/Release/
  - file ./bin/Release/*
#  - $QEMU_INTERPRETER ./bin/Release/spookyhash-test
